### PR TITLE
Implement some TypeExpr and Variable

### PR DESCRIPTION
**Pull request by akm**
- TypeExpr
    - ClassExpr
    - RecordExpr
    - ArrayExpr
    - Enum
- Variable

### CODE REVIEW

**Comment by akm** [comment]
Sorry again....

**Comment by gonutz** [comment]
Why do you keep opening and closing pull requests? :-)

**Comment by akm** [comment]
I just wanted to make a PR for forked repository, but PRs is initially made to merge to the original repository and I forgot to change it 3 times. Now, I made a PR template to check the destination to merge.

**Comment by gonutz** [comment]
I see, no problem :-)

**Pull request closed without merging**
